#pragma once

enum class AttackType
{
    MOUSEJACKING,
    ROLLJAM,
    BRUTEFORCE,
    DIP_SWITCH,
    JAMMING,
    SMART_HOME_REPLAY,
    SMART_HOME,
    WEATHER_STATION,
    VEHICLE_DIAGNOSTICS,
    KEY_FOB_EXTENSION,
    RF_REMOTE_OVERRIDE,
    WIRELESS_DOORBELL
};
